version: '3.3'

networks:
  postgres-net:
    driver: bridge

services:
  app:
    build: project
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mongodb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres?currentSchema=public
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/mydatabase
    networks:
      - postgres-net

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-net

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - postgres-net
    volumes:
      - mongodb-data:/data/db

volumes:
  postgres-data:
  mongodb-data: