version: '3.3'

networks:
  postgres-net:
    driver: bridge

services:
  app:
    build: project
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mongodb
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres?currentSchema=public
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/mydatabase
    networks:
      - postgres-net

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-net

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - postgres-net
    volumes:
      - mongodb-data:/data/db

  keycloak:
    depends_on:
      - db
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
      KC_FEATURES: scripts
      KEYCLOAK_ADMIN: user
      KEYCLOAK_ADMIN_PASSWORD: password
    command: start-dev --import-realm --verbose
    volumes:
      - ./keycloak/imports:/opt/keycloak/data/import
    image: quay.io/keycloak/keycloak:26.0.7
    ports:
      - "29000:8080"
    restart: unless-stopped
    networks:
      - postgres-net

volumes:
  postgres-data:
  mongodb-data:
