spring:
  application:
    name: project
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: true
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      globally_quoted_identifiers: true
      show_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 148014085259-mtaqcvl0nm5t7tmb8r2iugf664pk9rc1.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080
        provider:
          google:
            token-uri: https://oauth2.googleapis.com/token
  main:
    allow-bean-definition-overriding: true

  mvc:
    pathmatch:
      matching-strategy=ant_path_matcher:logging:
  level:
    root: INFO
mercado-pago:
  access-token: TEST-6546844616028207-063020-f09a0b6563261874ab236fd560e23d9b-769812162
  user-id: 769812162
  pos: SUC001POS002
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha